### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by QwertyZW**
This is my first real pull request.

It provides a GUI input prompt for the "watch" and "privatekey" json properties of .ftpconfig. For "privatekey" it allows file browsing on highlight of the "privatekey" line in order to select a path to a file key (will be escaped if it's a windows path.) For the "watch" property it provides an "Add" prompt which allows the user to select multiple files to add to her watch list.

The main file config-view.js is heavily commented for educational purposes

remote-ftp is the first atom package that I've started using and I've been using it for quite a while now. 

Thanks.

Update:
  Fixed issues pointed out by @jimmaaay 
  Added a permanently dismissable notification that informs user of features
  For the watch property: added a button that lets you add directories (although one at a time)

PS: "zaid usama" and khishman are both myself. git config user.name isn't working for some reason :/
Commits are made from several different machines.

### CODE REVIEW

**Comment by jimmaaay** [comment]
Hey I've been reviewing this and I like the idea, but feel as though it is not right for this project. As I believe it's not very user friendly. This is due to how you must know to hover over the highlighted line number which then shows a popup. I feel as though something similar to how Nuclide edits the configurations would be better, see [here](https://nuclide.io/static/images/docs/promo-remote-development.png). There's also a few other issues I noticed:
- Watch path is meant to be relative not absolute
- Buttons look weird on taller or shorter screen sizes

**Comment by QwertyZW** [comment]
I fixed both issues. I will add a small notification that tells the user that they can hover over the highlights.

I did consider building a separate configuration panel but that will adda whole level of complexity and introduce a new learning curve to current users. I figured something like that would require discussion with the package maintainers as opposed to what I implemented here, which is supposed to be a basic addon 

What I have here is meant to be a quick and easy way to edit your paths that's less error prone than the manual method.  I'm talking about general path errors, etc. For example when I first started using this package I didn't know that I had to escape \ for the paths to work on Windows. The addon does that automatically for you.

Reference: https://github.com/mgrenier/remote-ftp/issues/440 , #562

**Comment by QwertyZW** [comment]
There's your notification @jimmaaay .

**Comment by jimmaaay** [comment]
I'll have a look over this in the next few days.

**Comment by QwertyZW** [comment]
Synced with mgrenier/remote-ftp/dev, made GUI race condition a lot less likely (was already very unlikely).

**Comment by jimmaaay** [comment]
Sorry I know you've done a lot of work on this but I feel as though it still doesn't fit well. As I said previously something like how Nuclide manages the details with a popup, where perhaps you could edit the whole of the ftpconfig file would be better.

**Comment by QwertyZW** [comment]
Sure, np. Will look into it.

I still think a big feature like that might require discussion with @mgrenier  at least. If you don't think so I think I can start coding it up. @jimmaaay

**Pull request closed without merging**
