### PR TITLE
Ask for password dialog should also work for passphrase.

### PR DESCRIPTION
**Pull request by wdacgrs**
Most people using key file authentication for SFTP should find this one useful. :)

### CODE REVIEW

**Comment by Drod246** [comment]
Fuck, what I wouldn't do to never get another email on this issue. I've
tried to remove myself from it on github.

**Comment by jpxd** [comment]
@wdacgrs  Could you please document this feature in the README somehow? :)
Just that people know they can use the promtForPass option for FTP conns AND encrypted privkeys

**Comment by wdacgrs** [comment]
@jpxd I updated the README. :)

**Comment by jpxd** [comment]
Thx :)

**Pull request merged**
