### PR TITLE
Ask for password feature

### PR DESCRIPTION
**Pull request by wasikuss**
Added `prompt_for_pass` config option for password asking.

### CODE REVIEW

**Comment by phawxby** [comment]
Can you document that in the readme please?

**Comment by wasikuss** [comment]
Both suggestions are done.

**Comment by jpxd** [comment]
Btw: What do you think about just forgetting the extra option for `.ftpconfig` and ask for a password everytime there is none set in the config file ?  @wasikuss

**Comment by jpxd** [comment]
Forget about that, apparently there can be FTP servers with empty passwords...

**Comment by jpxd** [comment]
Yep this breaks, because you called on the prototype and not on **this**
I will test this now and squash it all in one commit
Thanks for your commitment!

**Comment by jpxd** [comment]
Okay I fixed it now and updated the property and function names to be in CamelCase like the others.
https://github.com/jpxd/remote-ftp/commit/d033414c652db669907675ba432d22adbb067f43
I will now merge it manually, that way we only have one feature-commit in the commit history.

**Comment by jpxd** [comment]
Tested it and it works
Any way we can get the password in the textbox to be hidden and not be visible? @wasikuss

**Comment by jpxd** [comment]
It's there! I'll open another issue for the password thing

**Pull request closed without merging**
