### PR TITLE
Added ability to download fresh copies of local files

### PR DESCRIPTION
**Pull request by MikeWillis**
While browsing the local tree view, user can now select local files, right click, and click a new "Download" option which downloads a fresh copy of the file from the remote location. FTP connection is created if necessary.

### CODE REVIEW

**Comment by jimmaaay** [comment]
@MikeWillis Thanks for the work on this :) This will be in the next release.

**Comment by MikeWillis** [comment]
Anytime!

Unfortunately I just found a bug. On the branch where no ftp connection exists, it initiates a reconnect and then does `atom.project.remoteftp.on('connected', function () {` which triggers download-selected-local. That's a mistake - from this point forward, any time the script re-connects, it always triggers download-selected-local.

Working on a fix now

**Comment by MikeWillis** [comment]
Fixed in my branch, should I create a new pull request? For some reason it's marking both modified files (client.js and remote-ftp.js) as completely new. No idea why it's doing that... Here's a summary of the fix:

client.js:
-- on failed connection, emit 'connectionFailed'

remote-ftp.js:
-- added a boolean flag: downloadSelectedLocalAwaitingConnection to module.exports, false by default
-- on 'connected' event:
---- if downloadSelectedLocalAwaitingConnection is true:
------ set it to false
------ initiate download-selected-local
-- if download-selected-local is triggered and a connection does not exist:
---- downloadSelectedLocalAwaitingConnection is set to true
---- remote-ftp:connect is initiated
-- on 'connectionFailed' event:
---- set downloadSelectedLocalAwaitingConnection to false (just in case a connection fails, if the flag is left as 'true' then a later successful connection will trigger a download, whether desired or not)

**Comment by jimmaaay** [comment]
Already noticed the bug. I'm pretty sure all I need to do to rectify it is to change `on('connected'` to `once('connected'`

**Comment by MikeWillis** [comment]
Nice! I knew what I came up with was overly complicated, glad you have a much simpler fix :)

**Comment by hatzopoulos** [comment]
> Fixed in my branch, should I create a new pull request?

I don't think that's necessary. 

Just add the commit fix to your working copy. Then rebase your working copy in order to `fixup` and squash your commit. Then push it to your fork using the --force argument, and this PR will get updated. 

Or if no one else cares about neatness, just make the commit fix and push it to your fork to update this PR.

**Comment by MikeWillis** [comment]
Thanks, I'll remember that for the future, I'm just getting familiar with github

**Comment by samifouad** [comment]
@MikeWillis The last time I actively contributed to an open source project was back when sourceforge was the de facto standard, so you're definitely not the only one who's still getting used to github. ;)

**Comment by MikeWillis** [comment]
@samifouad haha thanks I'm glad it's not just me!

**Pull request merged**
