### PR TITLE
Use new Filesystem Watcher API

### PR DESCRIPTION
**Pull request by putterson**
#980

### CODE REVIEW

**Comment by icetee** [comment]
It does not work for me. Atom 1.21.1

**Comment by putterson** [comment]
What platform are you trying on? If you're on linux, check out the issue currently affecting atom 1.21 on linux atom/atom#15642 . If not, do you get any exceptions/errors in your dev console that might point towards the issue?

**Comment by icetee** [comment]
Working sorry. I change native operation system APIs in Settings View. (macOS)

**Comment by putterson** [comment]
No problem. Regardless, my warning on issue #980 stands. I don't think this should be merged/released until the atom issue on linux is fixed.

**Comment by icetee** [comment]
Because of this pr/issue a new major version number must be entered. While not good at Linux, I'am not releasing 2.x version. If the Hackoktoberfest is important for you, I can merge!

**Comment by putterson** [comment]
Hey, don't sweat merging if you shouldn't. Not sure I'm going to be able to meet my hacktoberfest goals anyways. Also I'm not sure merging the PR is actually necessary for Hacktoberfest, just creating one.

**Pull request merged**
