### PR TITLE
.ftpignore feature from issue #36

### PR DESCRIPTION
**Pull request by josephmiclaus**
## .ftpignore feature from issue #36

After finding some time, this adds the wished feature of having a .ftpignore file, similar to the .gitignore file, as proposed by @mgrenier.

**Features**
- Create .ftpignore file from menu
- Edit .ftpignore file from FTP DirectoryView
- Ignore files & directories using [kaelzhang/node-ignore](https://github.com/kaelzhang/node-ignore) as proposed by @hatzopoulos
- Restricts upload or local-to-remote sync of .ftpconfig file for security reasons. (Was this a bug?)

**Restrictions**
- Only works with the first project path for now. _tl;dr_ I even stumbled on @mgrenier's issue from February https://github.com/atom/atom/issues/5613 regarding paths and multiple projects.
- Not sure, but it seems that _kaelzhang/node-ignore_ still has some issues?

**Further notes**
- Couldn't test ignoring of whole directories on local-to-remote sync (just upload), since it doesn't seem to do the job - again for directories only.
- Requires some testing.

### CODE REVIEW

**Comment by josephmiclaus** [comment]
has anybody had a look at this ?

(there are merge conflicts in the meantime)

**Comment by grenierdev** [comment]
Can you update the PR with latest commit?

**Comment by josephmiclaus** [comment]
I'll check it out soon .

EDIT : I'm sorry, I won't be able to fix this for the coming time . (lots to do)

**Comment by abumalick** [comment]
We really need this.
Keep up with your work !

**Comment by miclaus** [comment]
@mgrenier i quickly merged the current master branch into the forked master branch, but haven't tested this yet.. i'm testing it now.

**Comment by josephmiclaus** [comment]
@mgrenier this should do the job. please take a look at it! sorry for the delay!

**also**, a lot has changed in the meantime, so some parts will need a follow-up update, but i'll leave that to someone else.

**Comment by 4ley** [comment]
@miclaus Thanks a lot! I would love to see this merged soon!

**Comment by jpxd** [comment]
Nice, but we have to make clear somehow that this ONLY affects the local-to-remote sync...
E.g. in auto upload ignored files are uploaded anyway

**Comment by josephmiclaus** [comment]
@jpxd thanks, that i did not see. i don't think it would be a lot to extend the current implementation for auto upload as well. i added a helper function to `omitIgnored(locals)`, which can be used. however, as already noted, this only works w/ the first project directory, and could use some improvements.

whoever has time to implement this is happily welcome, since it will be a while until i may. 

anyhow it would be motivating to see this **finally** merged..

**Comment by jpxd** [comment]
We have enough other issues with anything other than the first project directory so I don't see a problem there for now.
Is it possible to add a comment to the top of the .ftpignore file to point out that this is a beta-feature and only works with local-to-remote sync? Then I would merge right away. I already tested your PR and it looks good. The merge conflict is just needs a small change in the package.json.

**Comment by josephmiclaus** [comment]
@jpxd yes can do in the course of the day. thanks!

**Comment by josephmiclaus** [comment]
@jpxd please check it out, i added the comment 😸 .

**Comment by dextermb** [comment]
What's the status of getting these features added? an `ignore` option for files or directories would be so useful!

**Comment by miclaus** [comment]
@dextermb i believe this has already been merged into master. so you may already create the `.ftpignore` over the provided menus. however as mentioned above this currently works for local-to-remote sync and also for the first project only.

have you tested it out yet ?

**Comment by icetee** [comment]
They started writing before, but did not finish. #668

It will resume soon develop.

**Pull request merged**
