### PR TITLE
Add support for multiple hosts #212

### PR DESCRIPTION
**Pull request by zxwef**
- Added support for multiple hosts (select any project with .ftpconfig and click connect).
- Added disconnect option in context-menu sidebar.

### CODE REVIEW

**Comment by jimmaaay** [comment]
Will look over this pr in the next few days

**Comment by hatzopoulos** [comment]
Linking #212

**Comment by jimmaaay** [comment]
@zxwef Your amends are now in 0.9.0. You will need to enable multiple hosts in the package preferences to use it.

**Comment by Rahulnigam28** [comment]
I have checked multiple hosts in the preferences. What do I need to put in the .ftpconfig file to include multiple hosts?

**Pull request merged**
